### ISSUE TITLE
Services we offer

### ISSUE THREAD

**Issue by Luis-Jones-Coder** [Luis-Jones-Coder/boardwalk-games#5]
**User Story**
As a Potential Customer, I would like to know what types of services you offer, so I can understand if they meet my needs.

**Acceptance Criteria**

- [ ] The website features a dedicated section that clearly lists and describes the services offered.
- [ ] This section is easily accessible from the main navigation and other key areas of the website.

**Tasks**

- [ ] Design and create a section that details the types of services offered, using information provided by the client.
- [ ] Ensure this services section is prominently visible and accessible from the main navigation menu and other key areas of the website, adhering to common design standards.
